---
- hosts: localhost
  connection: local
  tasks:
    - name: Build resource list
      command: buildresource.py /resources/resourceConfigFile
      register: inputList
    
    - name: Parse resource list
      set_fact:
        resourceList: "{{ inputList.stdout | from_json }}"
        
    - name: Delete S3 Buckets
      s3_bucket:
        name: "{{ item }}"
        state: absent
        force: yes
      with_items:
        "{{ resourceList.s3 | default([]) }}"

    - name: Delete DynamoDB Tables
      dynamodb_table:
        name: "{{ item }}"
        region: "{{ resourceList.dynamodb[item].region }}"
        hash_key_name: "{{ resourceList.dynamodb[item].hash_key_name }}"
        state: absent
      with_items:
        "{{ resourceList.dynamodb | default([]) }}"