version: '2'

services:
   dresource:
      image: drunner/dresource
      environment:
         - USERNAME
         - AWS_ACCESS_KEY
         - AWS_SECRET_KEY
      volumes:
         - "${RESOURCE_FILE}:/resources/resourceConfigFile"
      network_mode: "bridge"
