version: '2'

services:
   dresource:
      image: drunner/dresource
      environment:
         - RESOURCE_USERNAME
         - AWS_ACCESS_KEY_ID
         - AWS_SECRET_ACCESS_KEY
      volumes:
         - "${RESOURCE_FILE}:/resources/resourceConfigFile"
      network_mode: "bridge"
